### ISSUE TITLE
StatusCode: 400 Invalid Authorization Header content

### ISSUE THREAD

**Issue by minkobinko** [pierre0210/NovelAI-bot#1]
![image](https://user-images.githubusercontent.com/116066850/196376812-ee11d3da-00e0-478a-9c0b-ea5864a049c2.png)

**Comment by pierre0210** [comment]
You need to add a NovelAI access token to `.env` file. The access token looks something like "Bearer <some hash>" and can be found using chrome dev tool.

**Comment by minkobinko** [comment]
> You need to add a NovelAI access token to `.env` file. The access token looks something like "Bearer " and can be found using chrome dev tool.

I have already put the token in the env file and its still giving out the error

**Comment by nakamuraao** [comment]
Did you change `example.env` into `.env`?

**Comment by minkobinko** [comment]
> Did you change `example.env` into `.env`?

Yes
![image](https://user-images.githubusercontent.com/116066850/196383320-e8df1c86-333a-4ff5-a7d7-41a12559034b.png)
[](url)
![Screenshot (554)](https://user-images.githubusercontent.com/116066850/196383907-d7acd570-7110-476e-bd2f-f32b0fc96231.jpg)

**Comment by nakamuraao** [comment]
Looks like your novelai token is not right.
The word 'Bearer' should be in the front.
Just like `Bearer xxxxxxxxx`.

**Comment by minkobinko** [comment]
> Looks like your novelai token is not right. The word 'Bearer' should be in the front. Just like `Bearer xxxxxxxxx`.

Ahh I see, didn't realize I had to leave 'Bearer' in. Its working now thank you very much :D

**Comment by xSonicWavex** [comment]
Where did you find the Bearer Token? I see Bearer, but I only see Bearer + n.auth.token
