### ISSUE TITLE
how do you set up the bot? what should config.json look like?

### ISSUE THREAD

**Issue by TARSgts** [pierre0210/NovelAI-bot#2]
im having an issue seting up the bot and in general, I dont really undestand how to do it, I have my bot token and novel token but idk how to set up the config file

**Comment by TARSgts** [comment]
im having an issue seting up the bot and in general, I dont really undestand how to do it, I have my bot token and novel token but idk how to set up the config file

**Comment by pierre0210** [comment]
when you run the bot for the first time it will generate a `config.json` under `prod` folder you can change the language setting there, the bot & novelAI token should be filled into `example.env` file and then change the file name to `.env`.

**Comment by TARSgts** [comment]
I ran the code and I dont see the config.json, i do see tsconfig.json tho?

![image](https://user-images.githubusercontent.com/119083748/204348860-6352ed52-fe4a-461f-a7cb-4158ca9035b1.png)

**Comment by pierre0210** [comment]
Fixed in the latest commit, sorry for the misunderstanding.
