### ISSUE TITLE
statusCode: 400, 'model must be a valid enum value, model should not be empty, model must be a string'

### ISSUE THREAD

**Issue by purplemenace** [pierre0210/NovelAI-bot#3]
after submitting the form with a model input other than 'NAI Diffusion Anime (Curated)', I get this error. Is there any way to set up the other 2 models?
![image](https://user-images.githubusercontent.com/120114988/206480622-3b6be80f-ed4c-4f50-892b-2ef8c40a2e81.png)

**Comment by pierre0210** [comment]
Which model did you choose? There's only three model `NAI Diffusion Anime (Curated)` `NAI Diffusion Anime (Full)` `NAI Diffusion Furry (Beta)` discord.js doesn't support using drop down menu in modal currently so you will have to input the model name manually.

**Comment by purplemenace** [comment]
Oh I see now, thanks for clearing that up!
